# Generated by Django 4.2.6 on 2023-10-18 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_member', to=settings.AUTH_USER_MODEL)),
                ('second_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
