# Generated by Django 4.2.6 on 2023-10-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_chat_first_member_remove_chat_second_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
