# Generated by Django 4.2.6 on 2023-10-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.BigIntegerField(default=None),
        ),
    ]
